import React, { useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Sparkles, Send, Bot, User, Lightbulb } from "lucide-react";
import { aiChat } from "../api";
import { useChat } from "../context/ChatContext";

const SUGGESTIONS = [
  "Summarise the latest environmental alerts in Chhattisgarh.",
  "Which regions currently have the poorest air quality and why?",
  "Explain today's water quality status for monitored rivers.",
  "Suggest 3 actions industries can take to improve compliance.",
];

export default function AiAssistantPage() {
  const { messages, setMessages } = useChat();
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const bottomRef = useRef(null);

  const scrollToBottom = () => {
    if (bottomRef.current) {
      bottomRef.current.scrollIntoView({ behavior: "smooth", block: "end" });
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading]);

  const sendMessage = async (text) => {
    const trimmed = text.trim();
    if (!trimmed || loading) return;
    setError("");

    const userMsg = {
      id: `user-${Date.now()}`,
      role: "user",
      content: trimmed,
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    const historyPayload = [...messages, userMsg].map((m) => ({
      role: m.role,
      content: m.content,
    }));

    const res = await aiChat(trimmed, historyPayload);
    setLoading(false);

    if (!res.ok) {
      setError(res.data?.error || "AI assistant is unavailable.");
      return;
    }

    const aiMsg = {
      id: `ai-${Date.now()}`,
      role: "assistant",
      content: res.data.reply || "",
    };

    setMessages((prev) => [...prev, aiMsg]);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    void sendMessage(input);
  };

  const handleSuggestion = (s) => {
    setInput(s);
    void sendMessage(s);
  };

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "minmax(220px, 260px) 1fr",
        height: "100%",
        gap: "0",
        background: "#e5e7eb",
      }}
    >
      {/* Sidebar */}
      <aside
        style={{
          borderRight: "1px solid #d1d5db",
          padding: "18px 16px",
          display: "flex",
          flexDirection: "column",
          gap: "16px",
          background: "#f3f4f6",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div
            style={{
              width: 26,
              height: 26,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background:
                "var(--govt-blue)",
              color: "white",
            }}
          >
            <Sparkles size={16} />
          </div>
          <div>
            <div className="label-box" style={{ marginBottom: 4 }}>PrithviNet Copilot</div>
            <div className="text-box text-box-blue" style={{ fontSize: "0.9rem", fontWeight: 600, marginBottom: 0 }}>Ask about your data</div>
          </div>
        </div>

        <div className="text-box text-box-grey" style={{ fontSize: "0.78rem", lineHeight: 1.5, marginBottom: 0 }}>
          The assistant has access to recent alerts, regional offices and monitoring
          data. It will not make changes — only explain and summarise.
        </div>

        <div style={{ marginTop: 8, display: "flex", flexDirection: "column", gap: 8 }}>
          <div className="label-box" style={{ marginBottom: 0 }}>Suggested questions</div>
          {SUGGESTIONS.map((s) => (
            <button
              key={s}
              onClick={() => handleSuggestion(s)}
              className="text-box text-box-blue"
              style={{
                textAlign: "left",
                padding: "10px 12px",
                fontSize: "0.8rem",
                marginBottom: 0,
                color: "var(--text-secondary)",
                display: "flex",
                gap: 6,
                alignItems: "flex-start",
                cursor: "pointer",
              }}
            >
              <Lightbulb size={14} style={{ marginTop: 2 }} />
              <span>{s}</span>
            </button>
          ))}
        </div>
      </aside>

      {/* Chat column */}
      <section
        style={{
          display: "flex",
          flexDirection: "column",
          height: "100%",
          background: "#e5e7eb",
        }}
      >
        <div className="text-box text-box-amber" style={{ padding: "12px 20px", borderBottom: "1px solid #d1d5db", marginBottom: 0, borderRadius: 0 }}>
          Conversations are generated by a local Ollama model (
          <code>qwen2.5:0.5b</code>). Please verify important decisions with experts.
        </div>

        <div
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "16px 20px",
            display: "flex",
            flexDirection: "column",
            gap: 12,
            background: "#e5e7eb",
          }}
        >
          {messages.map((m) => (
            <ChatMessage key={m.id} role={m.role} content={m.content} />
          ))}
          {loading && (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                fontSize: "0.8rem",
                color: "#6b7280",
              }}
            >
              <Bot size={14} />{" "}
              <span className="typing-indicator">
                Thinking<span>.</span>
                <span>.</span>
                <span>.</span>
              </span>
            </div>
          )}
          {error && (
            <div
              style={{
                fontSize: "0.8rem",
                color: "#b91c1c",
                border: "1px solid rgba(248,113,113,0.5)",
                padding: "8px 10px",
              }}
            >
              {error}
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        <form
          onSubmit={handleSubmit}
          style={{
            borderTop: "1px solid #d1d5db",
            padding: "10px 20px",
            display: "flex",
            gap: 10,
            alignItems: "center",
            background: "#f9fafb",
          }}
        >
          <input
            type="text"
            placeholder="Ask about alerts, regions, industries or trends..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            style={{
              flex: 1,
              padding: "10px 12px",
              border: "1px solid #d1d5db",
              fontSize: "0.9rem",
              background: "#fff",
            }}
          />
          <button
            type="submit"
            disabled={loading || !input.trim()}
            style={{
              padding: "9px 14px",
              display: "flex",
              alignItems: "center",
              gap: 6,
              fontSize: "0.85rem",
              fontWeight: 600,
              background:
                "var(--govt-blue)",
              color: "white",
              border: "none",
              opacity: loading || !input.trim() ? 0.7 : 1,
            }}
          >
            <Send size={14} />
            Send
          </button>
        </form>
      </section>
    </div>
  );
}

function ChatMessage({ role, content }) {
  const isUser = role === "user";
  return (
    <div
      style={{
        alignSelf: isUser ? "flex-end" : "flex-start",
        maxWidth: "80%",
        display: "flex",
        gap: 8,
        flexDirection: isUser ? "row-reverse" : "row",
      }}
    >
      <div
        style={{
          width: 26,
          height: 26,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: isUser ? "#dbeafe" : "#9ca3af",
          color: isUser ? "#1d4ed8" : "#fff",
        }}
      >
        {isUser ? <User size={14} /> : <Bot size={14} />}
      </div>
      <div
        style={{
          padding: "8px 10px",
          border: "1px solid #d1d5db",
          background: isUser ? "#fff" : "#d1d5db",
          color: isUser ? "#111827" : "#1f2937",
          fontSize: "0.9rem",
          lineHeight: 1.5,
          maxWidth: "100%",
        }}
      >
        {isUser ? (
          <span>{content}</span>
        ) : (
          <ReactMarkdown>{content}</ReactMarkdown>
        )}
      </div>
    </div>
  );
}

